### ISSUE TITLE
of QLIBS_USE_STD_MATH

### ISSUE THREAD

**Issue by tuomo16** [kmilo17pet/qfiscgen-MATLAB#1]
Works well. However in qffmath.h there is for selection of standard math:
#ifdef QLIBS_USE_STD_MATH
    /*! @cond  */
    #include <math.h.h>   // this one <---- math.h ?

BTW, Where is this selection made, we could not find?

BR, Tuomo and Anna

**Comment by kmilo17pet** [comment]
thanks @tuomo16 
yes is a typo, fixed!
just invoke the qfiscgen command again, he will bring the updated source files
